-- AlterEnum
ALTER TYPE "OtpContext" ADD VALUE IF NOT EXISTS 'PHONE_VERIFY';
ALTER TYPE "OtpContext" ADD VALUE IF NOT EXISTS 'EMAIL_VERIFY';

-- AlterTable
ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "phone_verified_at" TIMESTAMPTZ(6),
  ADD COLUMN IF NOT EXISTS "email_verified_at" TIMESTAMPTZ(6);
