export const HEALTH_THRESHOLDS = {
  HIGH_TRAFFIC_CONCURRENT_REQUESTS: 200,

  CRITICAL_CPU_PERCENT: 95,
  WARNING_CPU_PERCENT: 80,

  STORAGE_WARNING_PERCENT: 85,
  WARNING_TRAFFIC_CONCURRENT_REQUESTS: 120,
};
